export const columnsForExcelTable = [
  {
    title: "상품코드",
    dataIndex: "product_code",
    key: "product_code",
    type: "text",
    readOnly: false,
  },
  {
    title: "상품명",
    dataIndex: "product_name",
    key: "product_name",
    type: "text",
    readOnly: false,
  },
  { title: "카테고리", dataIndex: "category", key: "category", type: "text", readOnly: false },
  { title: "재고수량", dataIndex: "stock", key: "stock", type: "number", readOnly: false },
  { title: "판매수량", dataIndex: "sales", key: "sales", type: "number", readOnly: false },
  { title: "단가(원)", dataIndex: "price", key: "price", type: "number", readOnly: false },
  { title: "매출액(원)", dataIndex: "revenue", key: "revenue", type: "formula", readOnly: true },
];

export const dataForExcelTable = [
  {
    product_code: "C001",
    product_name: "아메리카노",
    category: "커피",
    stock: 120,
    sales: 85,
    price: 4500,
    revenue: 382500,
  },
  {
    product_code: "C002",
    product_name: "카페라떼",
    category: "커피",
    stock: 90,
    sales: 60,
    price: 5000,
    revenue: 300000,
  },
  {
    product_code: "C003",
    product_name: "바닐라라떼",
    category: "커피",
    stock: 70,
    sales: 50,
    price: 5500,
    revenue: 275000,
  },
  {
    product_code: "C004",
    product_name: "카푸치노",
    category: "커피",
    stock: 60,
    sales: 40,
    price: 5200,
    revenue: 208000,
  },
  {
    product_code: "C005",
    product_name: "콜드브루",
    category: "커피",
    stock: 80,
    sales: 45,
    price: 4800,
    revenue: 216000,
  },
  {
    product_code: "C006",
    product_name: "카페모카",
    category: "커피",
    stock: 65,
    sales: 35,
    price: 5700,
    revenue: 199500,
  },
  {
    product_code: "C007",
    product_name: "에스프레소",
    category: "커피",
    stock: 50,
    sales: 30,
    price: 4000,
    revenue: 120000,
  },
  {
    product_code: "C008",
    product_name: "플랫화이트",
    category: "커피",
    stock: 40,
    sales: 28,
    price: 5300,
    revenue: 148400,
  },
  {
    product_code: "C009",
    product_name: "더치라떼",
    category: "커피",
    stock: 55,
    sales: 25,
    price: 6000,
    revenue: 150000,
  },
  {
    product_code: "C010",
    product_name: "카라멜마끼아또",
    category: "커피",
    stock: 70,
    sales: 42,
    price: 5900,
    revenue: 247800,
  },

  {
    product_code: "B011",
    product_name: "녹차라떼",
    category: "음료",
    stock: 60,
    sales: 35,
    price: 5500,
    revenue: 192500,
  },
  {
    product_code: "B012",
    product_name: "초코라떼",
    category: "음료",
    stock: 65,
    sales: 40,
    price: 5600,
    revenue: 224000,
  },
  {
    product_code: "B013",
    product_name: "고구마라떼",
    category: "음료",
    stock: 50,
    sales: 32,
    price: 5700,
    revenue: 182400,
  },
  {
    product_code: "B014",
    product_name: "밀크티",
    category: "음료",
    stock: 70,
    sales: 45,
    price: 6000,
    revenue: 270000,
  },
  {
    product_code: "B015",
    product_name: "얼그레이티",
    category: "음료",
    stock: 40,
    sales: 25,
    price: 4500,
    revenue: 112500,
  },
  {
    product_code: "B016",
    product_name: "레몬에이드",
    category: "음료",
    stock: 80,
    sales: 50,
    price: 5200,
    revenue: 260000,
  },
  {
    product_code: "B017",
    product_name: "청포도에이드",
    category: "음료",
    stock: 75,
    sales: 42,
    price: 5300,
    revenue: 222600,
  },
  {
    product_code: "B018",
    product_name: "자몽에이드",
    category: "음료",
    stock: 70,
    sales: 40,
    price: 5400,
    revenue: 216000,
  },
  {
    product_code: "B019",
    product_name: "유자차",
    category: "음료",
    stock: 50,
    sales: 28,
    price: 5000,
    revenue: 140000,
  },
  {
    product_code: "B020",
    product_name: "생강차",
    category: "음료",
    stock: 40,
    sales: 20,
    price: 5200,
    revenue: 104000,
  },

  {
    product_code: "D021",
    product_name: "치즈케이크",
    category: "디저트",
    stock: 30,
    sales: 18,
    price: 6500,
    revenue: 117000,
  },
  {
    product_code: "D022",
    product_name: "티라미수",
    category: "디저트",
    stock: 25,
    sales: 15,
    price: 6800,
    revenue: 102000,
  },
  {
    product_code: "D023",
    product_name: "브라우니",
    category: "디저트",
    stock: 40,
    sales: 22,
    price: 5500,
    revenue: 121000,
  },
  {
    product_code: "D024",
    product_name: "허니브레드",
    category: "디저트",
    stock: 20,
    sales: 12,
    price: 7500,
    revenue: 90000,
  },
  {
    product_code: "D025",
    product_name: "마카롱세트",
    category: "디저트",
    stock: 35,
    sales: 20,
    price: 7200,
    revenue: 144000,
  },
  {
    product_code: "D026",
    product_name: "크루아상",
    category: "디저트",
    stock: 50,
    sales: 30,
    price: 4800,
    revenue: 144000,
  },
  {
    product_code: "D027",
    product_name: "스콘",
    category: "디저트",
    stock: 45,
    sales: 28,
    price: 5000,
    revenue: 140000,
  },
  {
    product_code: "D028",
    product_name: "레몬머랭파이",
    category: "디저트",
    stock: 20,
    sales: 10,
    price: 7800,
    revenue: 78000,
  },
  {
    product_code: "D029",
    product_name: "애플파이",
    category: "디저트",
    stock: 25,
    sales: 15,
    price: 6900,
    revenue: 103500,
  },
  {
    product_code: "D030",
    product_name: "블루베리머핀",
    category: "디저트",
    stock: 40,
    sales: 22,
    price: 5200,
    revenue: 114400,
  },

  {
    product_code: "S031",
    product_name: "베이글",
    category: "스낵",
    stock: 30,
    sales: 18,
    price: 4300,
    revenue: 77400,
  },
  {
    product_code: "S032",
    product_name: "햄치즈샌드위치",
    category: "스낵",
    stock: 25,
    sales: 14,
    price: 5800,
    revenue: 81200,
  },
  {
    product_code: "S033",
    product_name: "치킨랩",
    category: "스낵",
    stock: 20,
    sales: 12,
    price: 6200,
    revenue: 74400,
  },
  {
    product_code: "S034",
    product_name: "클럽샌드위치",
    category: "스낵",
    stock: 15,
    sales: 10,
    price: 6500,
    revenue: 65000,
  },
];
